// GENERATED by scripts/process-brochure-images.cjs from the 2026 product brochure — re-run that
// script (or edit by hand) rather than renaming files in public/images/brands-gallery/.
//
// Keyed by the brand `name` in content.ts. A brand with no entry here (currently Geberit and MCM
// Ittim — the brochure has no section for them) shows "Photos coming soon" in the brand detail
// view. `preview` is the small lazy-loaded grid image, `full` the one the zoom viewer opens;
// width/height are the full image's size so tiles reserve their space and never shift layout.

export interface GalleryPhoto {
  preview: string
  full: string
  width: number
  height: number
  alt: string
}

export const brandGallery: Record<string, GalleryPhoto[]> = {
  "Verantes Living": [
    { preview: "/images/brands-gallery/verantes-living/01-timber-kitchen-island-preview.webp", full: "/images/brands-gallery/verantes-living/01-timber-kitchen-island.webp", width: 1280, height: 1600, alt: "Modular kitchen with timber-toned shutters, a long island and dining area" },
    { preview: "/images/brands-gallery/verantes-living/02-kitchen-island-top-view-preview.webp", full: "/images/brands-gallery/verantes-living/02-kitchen-island-top-view.webp", width: 768, height: 960, alt: "Top-down view of a kitchen island with dining counter and hob" },
    { preview: "/images/brands-gallery/verantes-living/03-copper-finish-details-preview.webp", full: "/images/brands-gallery/verantes-living/03-copper-finish-details.webp", width: 600, height: 776, alt: "Copper-finish stainless steel drawers, shelving and sink area" },
  ],
  "Grohe": [
    { preview: "/images/brands-gallery/grohe/01-shower-and-basin-set-preview.webp", full: "/images/brands-gallery/grohe/01-shower-and-basin-set.webp", width: 1296, height: 972, alt: "Grey-tiled bathroom with wall-mounted shower set, hand shower and basin mixer" },
    { preview: "/images/brands-gallery/grohe/02-wall-mounted-basin-mixer-preview.webp", full: "/images/brands-gallery/grohe/02-wall-mounted-basin-mixer.webp", width: 480, height: 536, alt: "Wall-mounted basin mixer with water running into a white basin" },
    { preview: "/images/brands-gallery/grohe/03-ceiling-rain-shower-preview.webp", full: "/images/brands-gallery/grohe/03-ceiling-rain-shower.webp", width: 561, height: 701, alt: "Ceiling-mounted rain shower in a dark stone shower room" },
    { preview: "/images/brands-gallery/grohe/04-gold-basin-mixer-preview.webp", full: "/images/brands-gallery/grohe/04-gold-basin-mixer.webp", width: 561, height: 701, alt: "Brushed-gold basin mixer and accessories beside a freestanding washbasin" },
  ],
  "Oyster": [
    { preview: "/images/brands-gallery/oyster/01-whirlpool-bath-preview.webp", full: "/images/brands-gallery/oyster/01-whirlpool-bath.webp", width: 1200, height: 1200, alt: "Whirlpool bath with lit hydro-massage jets on a timber deck" },
    { preview: "/images/brands-gallery/oyster/02-shower-panel-preview.webp", full: "/images/brands-gallery/oyster/02-shower-panel.webp", width: 720, height: 720, alt: "Black shower panel with body jets, rain head and hand shower" },
    { preview: "/images/brands-gallery/oyster/03-steam-and-sauna-preview.webp", full: "/images/brands-gallery/oyster/03-steam-and-sauna.webp", width: 720, height: 720, alt: "Steam and sauna room in glass and timber" },
    { preview: "/images/brands-gallery/oyster/04-freestanding-air-bath-preview.webp", full: "/images/brands-gallery/oyster/04-freestanding-air-bath.webp", width: 720, height: 720, alt: "Freestanding air-bath tub in a dark stone bathroom" },
  ],
  "Hansgrohe x Axor": [
    { preview: "/images/brands-gallery/hansgrohe-x-axor/01-hansgrohe-blue-rain-shower-preview.webp", full: "/images/brands-gallery/hansgrohe-x-axor/01-hansgrohe-blue-rain-shower.webp", width: 1542, height: 858, alt: "Hansgrohe rain shower lit in blue in a tiled shower room" },
    { preview: "/images/brands-gallery/hansgrohe-x-axor/02-hansgrohe-rain-shower-head-preview.webp", full: "/images/brands-gallery/hansgrohe-x-axor/02-hansgrohe-rain-shower-head.webp", width: 706, height: 636, alt: "Close-up of a Hansgrohe rain shower head in use" },
    { preview: "/images/brands-gallery/hansgrohe-x-axor/03-hansgrohe-shower-system-preview.webp", full: "/images/brands-gallery/hansgrohe-x-axor/03-hansgrohe-shower-system.webp", width: 675, height: 651, alt: "Hansgrohe shower system with shelf and thermostatic controls" },
    { preview: "/images/brands-gallery/hansgrohe-x-axor/04-hansgrohe-basin-mixer-preview.webp", full: "/images/brands-gallery/hansgrohe-x-axor/04-hansgrohe-basin-mixer.webp", width: 664, height: 890, alt: "Hand under water running from a Hansgrohe basin mixer" },
    { preview: "/images/brands-gallery/hansgrohe-x-axor/05-axor-mixer-at-dusk-preview.webp", full: "/images/brands-gallery/hansgrohe-x-axor/05-axor-mixer-at-dusk.webp", width: 1284, height: 993, alt: "Axor basin mixer standing in water at dusk" },
    { preview: "/images/brands-gallery/hansgrohe-x-axor/06-axor-rose-gold-mixer-preview.webp", full: "/images/brands-gallery/hansgrohe-x-axor/06-axor-rose-gold-mixer.webp", width: 540, height: 675, alt: "Axor rose-gold basin mixer with cross handles" },
    { preview: "/images/brands-gallery/hansgrohe-x-axor/07-axor-luxury-rain-shower-preview.webp", full: "/images/brands-gallery/hansgrohe-x-axor/07-axor-luxury-rain-shower.webp", width: 540, height: 675, alt: "Axor rain shower in a dark, blue-lit shower room" },
    { preview: "/images/brands-gallery/hansgrohe-x-axor/08-axor-shower-panel-preview.webp", full: "/images/brands-gallery/hansgrohe-x-axor/08-axor-shower-panel.webp", width: 540, height: 675, alt: "Axor shower panel in a bathroom with floor-to-ceiling windows" },
  ],
  "Vitra": [
    { preview: "/images/brands-gallery/vitra/01-bathroom-setting-preview.webp", full: "/images/brands-gallery/vitra/01-bathroom-setting.webp", width: 732, height: 735, alt: "Bathroom with freestanding washbasin, wall shelf and rose-gold shower" },
    { preview: "/images/brands-gallery/vitra/02-smart-toilet-preview.webp", full: "/images/brands-gallery/vitra/02-smart-toilet.webp", width: 354, height: 651, alt: "Smart wall-hung toilet in a warm-toned bathroom" },
    { preview: "/images/brands-gallery/vitra/03-yellow-tile-shower-preview.webp", full: "/images/brands-gallery/vitra/03-yellow-tile-shower.webp", width: 539, height: 674, alt: "Shower area with yellow wall tiles and wall-mounted controls" },
    { preview: "/images/brands-gallery/vitra/04-countertop-basin-preview.webp", full: "/images/brands-gallery/vitra/04-countertop-basin.webp", width: 539, height: 672, alt: "Countertop basin with tall mixer on a stone shelf" },
  ],
  "Dimore": [
    { preview: "/images/brands-gallery/dimore/01-lounge-and-staircase-preview.webp", full: "/images/brands-gallery/dimore/01-lounge-and-staircase.webp", width: 1205, height: 672, alt: "Large-format tiles in a stairwell and lounge interior" },
    { preview: "/images/brands-gallery/dimore/02-terrace-and-staircase-preview.webp", full: "/images/brands-gallery/dimore/02-terrace-and-staircase.webp", width: 479, height: 717, alt: "Concrete-look tiles on a modern terrace and staircase" },
    { preview: "/images/brands-gallery/dimore/03-patterned-dining-floor-preview.webp", full: "/images/brands-gallery/dimore/03-patterned-dining-floor.webp", width: 656, height: 656, alt: "Green and white patterned floor tiles in a dining room" },
  ],
  "Qutone": [
    { preview: "/images/brands-gallery/qutone/01-surface-cube-preview.webp", full: "/images/brands-gallery/qutone/01-surface-cube.webp", width: 1284, height: 993, alt: "Qutone surface cube resting on clouds at sunrise" },
    { preview: "/images/brands-gallery/qutone/02-botanical-lounge-wall-preview.webp", full: "/images/brands-gallery/qutone/02-botanical-lounge-wall.webp", width: 561, height: 701, alt: "Botanical-pattern wall surface behind a lounge sofa" },
    { preview: "/images/brands-gallery/qutone/03-black-floor-dining-hall-preview.webp", full: "/images/brands-gallery/qutone/03-black-floor-dining-hall.webp", width: 561, height: 701, alt: "Glossy black floor tiles in an arched dining hall" },
    { preview: "/images/brands-gallery/qutone/04-shower-and-basin-tiles-preview.webp", full: "/images/brands-gallery/qutone/04-shower-and-basin-tiles.webp", width: 561, height: 701, alt: "Tiled shower and basin area with warm brown walls" },
  ],
  "Nexion": [
    { preview: "/images/brands-gallery/nexion/01-stone-look-floor-preview.webp", full: "/images/brands-gallery/nexion/01-stone-look-floor.webp", width: 830, height: 1126, alt: "Stone-look floor tiles seen from above with chairs" },
    { preview: "/images/brands-gallery/nexion/02-marble-material-board-preview.webp", full: "/images/brands-gallery/nexion/02-marble-material-board.webp", width: 830, height: 597, alt: "Marble and stone tiles on a material mood board" },
    { preview: "/images/brands-gallery/nexion/03-wood-look-flooring-preview.webp", full: "/images/brands-gallery/nexion/03-wood-look-flooring.webp", width: 498, height: 676, alt: "Wood-look flooring in a bright room with a teal bench" },
    { preview: "/images/brands-gallery/nexion/04-terracotta-cladding-preview.webp", full: "/images/brands-gallery/nexion/04-terracotta-cladding.webp", width: 498, height: 676, alt: "Terracotta-toned exterior cladding on a modern building" },
  ],
}
