export type ProjectCategory = 'sanitaryware' | 'tiles' | 'kitchen' | 'wellness' | 'furniture'

export const CATEGORY_LABELS: Record<ProjectCategory, string> = {
  sanitaryware: 'Sanitaryware',
  tiles: 'Tiles',
  kitchen: 'Kitchen',
  wellness: 'Wellness',
  furniture: 'Furniture',
}

export interface ProductUsed {
  brand: string
  category: string
}

export interface BeforeAfterPair {
  before: string
  after: string
}

export interface Project {
  id: string
  title: string
  /** "Villa" | "Apartment" | "Office" | ... — a free string so new client
   * types can be added without a type change; the Projects page derives
   * its filter options from whatever values actually appear here. */
  clientType: string
  location: string
  description: string
  productsUsed: ProductUsed[]
  /** Which product categories this project touches, for filtering. */
  categories: ProjectCategory[]
  /** Gallery photo paths, first one used as the card cover. */
  images: string[]
  /** Only rendered if present — most projects won't have one. */
  beforeAfter?: BeforeAfterPair[]
}

/**
 * PLACEHOLDER DATA — these 3 projects (and their images under
 * public/images/projects/project-0N/, generated by
 * scripts/generate-project-placeholders.cjs) exist only so the Projects
 * page has something real to filter, paginate and render while it's being
 * built and tested. Nothing here — names, locations, descriptions,
 * photos — is a real Buildcon House project.
 *
 * To add a real project:
 * 1. Copy one of the objects below and give it a new unique `id`.
 * 2. Fill in the real title, clientType, location, description,
 *    productsUsed and categories.
 * 3. Create public/images/projects/<id>/ and drop real photos in it
 *    (any filenames), then point `images` (and `beforeAfter`, if you have
 *    before/after shots) at those paths instead of the placeholder SVGs.
 * 4. Delete the corresponding entry from the JOBS array in
 *    scripts/generate-project-placeholders.cjs so it never regenerates a
 *    placeholder over your real photos, and remove the placeholder
 *    project object once you no longer need it for layout testing.
 */
export const projects: Project[] = [
  {
    id: 'project-01',
    title: 'The Ashapura Villa',
    clientType: 'Villa',
    location: 'Rajkot',
    description:
      'A full ground-plus-one villa renovation for a family who wanted their kitchen and bathrooms to feel as considered as the rest of the home. We reworked the master and guest bathrooms around Grohe fittings and rebuilt the kitchen from scratch with Häcker Kitchens cabinetry, favouring quiet finishes and better storage over anything flashy.',
    productsUsed: [
      { brand: 'Grohe', category: 'Sanitaryware' },
      { brand: 'Häcker Kitchens', category: 'Kitchen' },
    ],
    categories: ['kitchen', 'sanitaryware'],
    images: [
      '/images/projects/project-01/gallery-1.svg',
      '/images/projects/project-01/gallery-2.svg',
      '/images/projects/project-01/gallery-3.svg',
      '/images/projects/project-01/gallery-4.svg',
      '/images/projects/project-01/gallery-5.svg',
    ],
    beforeAfter: [{ before: '/images/projects/project-01/before.svg', after: '/images/projects/project-01/after.svg' }],
  },
  {
    id: 'project-02',
    title: 'Riverfront Residency',
    clientType: 'Apartment',
    location: 'Ahmedabad',
    description:
      'A 3BHK apartment overlooking the Sabarmati riverfront, refitted with large-format Nexion tiles through the living areas and a Geberit-fitted wellness bathroom with a steam shower — the client wanted a small spa-like corner of the apartment without touching the rest of the layout.',
    productsUsed: [
      { brand: 'Nexion', category: 'Tiles' },
      { brand: 'Geberit', category: 'Sanitaryware' },
    ],
    categories: ['tiles', 'wellness'],
    images: [
      '/images/projects/project-02/gallery-1.svg',
      '/images/projects/project-02/gallery-2.svg',
      '/images/projects/project-02/gallery-3.svg',
      '/images/projects/project-02/gallery-4.svg',
    ],
  },
  {
    id: 'project-03',
    title: 'Suryakiran Corporate Office',
    clientType: 'Office',
    location: 'Rajkot',
    description:
      'A three-floor corporate office fit-out — Verantes Living furniture through the reception, cabins and break-out areas, paired with Vitra sanitaryware in every washroom. The brief was simple: it should feel like a serious, calm place to work, not a showroom.',
    productsUsed: [
      { brand: 'Verantes Living', category: 'Furniture' },
      { brand: 'Vitra', category: 'Sanitaryware' },
    ],
    categories: ['furniture', 'sanitaryware'],
    images: [
      '/images/projects/project-03/gallery-1.svg',
      '/images/projects/project-03/gallery-2.svg',
      '/images/projects/project-03/gallery-3.svg',
      '/images/projects/project-03/gallery-4.svg',
      '/images/projects/project-03/gallery-5.svg',
    ],
    beforeAfter: [{ before: '/images/projects/project-03/before.svg', after: '/images/projects/project-03/after.svg' }],
  },
]
